baseURL = 'https://Kshitij-Banerjee.github.io'
languageCode = 'en-us'
title = "KiloBytes by KB"
theme = 'PaperMod'
disqusShortname = "kshitij-banerjee"
googleAnalytics = "G-KFSE3K3EMC"
googleAnalytics_v4 = "G-KFSE3K3EMC"
[services]
  [services.disqus]
    shortname = 'kshitij-banerjee'
[params]
	comments = true
	comment = true
	defaultTheme = "light"
	disableThemeToggle = true
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
[permalinks]
  posts = "/:year/:month/:day/:slug/"
