baseURL: https://kshitijbanerjee.com
languageCode: en-us
title: KiloBytes by KB
subtitle: by KB
theme: PaperMod
disqusShortname: kshitij-banerjee
googleAnalytics: G-KFSE3K3EMC
googleAnalytics_v4: G-KFSE3K3EMC
services:
  disqus:
    shortname: kshitij-banerjee
params:
  comments: true
  comment: true
  defaultTheme: light
  disableThemeToggle: true
  homeInfoParams:
    enabled: true
    imageUrl: https://media.licdn.com/dms/image/v2/D5603AQHkfsx3jgN3kw/profile-displayphoto-shrink_400_400/B56ZWAGj1WGUAg-/0/1741610958543?e=1747872000&v=beta&t=yLaPAkSf98H_oPkulP6bYKYbH9u96NvW8d2iz42zG64
    title: "**Kshitij Banerjee (KB)**"
    subtitle: "*Thoughts on Management, Code generation with LLMs and ML Trading*"
  socialIcons:
    - name: "linkedin"
      url: https://www.linkedin.com/in/kshitijbanerjee/
    - name: "substack"
      url: https://kilobytes.substack.com/
    - name: "github"
      url: "https://github.com/Kshitij-Banerjee"
    - name: "email"
      url: "mailto:ksh.dce@gmail.com"
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
permalinks:
  posts: /:year/:month/:day/:slug/
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
markup:
  goldmark:
    renderer:
      unsafe: true
