baseURL = 'https://Kshitij-Banerjee.github.io'
languageCode = 'en-us'
title = "KiloBytes by KB"
theme = 'PaperMod'
[params]
defaultTheme = "light"
disableThemeToggle = true
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
[permalinks]
  posts = "/:year/:month/:day/:slug/"
